### PR TITLE
exposed Content-Encoding option to curl for addFile()

### PR DESCRIPTION
**Pull request by ybogdanov**
Hi,

Please, merge this change to allow uploading files with extra contentEncoding option (and other options in future).
The api is simple: users are able to add extra (not required) options object:

```
cloudfiles.addFile('container', 'remote_filename', '/path/to/local/file', { contentEncoding: 'gzip' }, function(err) {
      // ...
})
```

Thanks!

### CODE REVIEW

**Comment by indexzero** [comment]
@0ctave. Thanks. Can you add a test for this?

**Comment by ybogdanov** [comment]
So?

**Comment by ybogdanov** [comment]
Hi,

Nothing major. I've just removed the garbage in utils.js (removed special contentEncoding option, cause we can now use options.headers) and fixed tests.

**Comment by indexzero** [comment]
Looks good. Will cherry-pick these in tonight

**Comment by indexzero** [comment]
@0ctave I'm confused which commits I should pull in. It looks like this is the only relevant commit: 

https://github.com/0ctave/node-cloudfiles/commit/16aea68f15c331ecccbd95ed8af84f8a8fd0a6ff

Can you confirm? I've been moving towards a `cherry-pick` workflow so I can ignore your previous four commits (which according to your comments seem to be code you later removed?)

**Comment by indexzero** [comment]
@0ctave Ok. I got it. I didn't realize that @indutny had been working at the same time on `.addFile()`. In the future, try to avoid merge commits. Generally you can try something like:

``` bash
  $ git checkout -b merge
  $ git checkout [last good commit that will avoid merge]
  $ git cherry-pick [your commit]
  $ [resolve conflicts]
  $ git commit -c [your commit]
```

This will avoid any merge commits. Thanks!

**Comment by indutny** [comment]
Sorry! I was experimenting with my [connect-cdn](https://github.com/indutny/connect-cdn) module. And found that Firefox needs some additional cross-origin headers to include fonts from other domains (Like cloudfiles CDN). So I added this options to node-cloudfiles.

I'm sure it's not breaking anything. And should be cool for future usage ;)

**Comment by indexzero** [comment]
@indutny No worries, you didn't do anything wrong. The problem was in the git workflow around the pull-request which led to merge commits. You're (as always) welcome to make commits to HEAD :-D

**Pull request closed without merging**
