### PR TITLE
0.6 compatibility

### PR DESCRIPTION
**Pull request by mmalecki**
Can someone run tests on it?

### CODE REVIEW

**Comment by Marak** [comment]
@mmalecki  - Thanks for opening this. 

We'll get you an account on rackspace soon so you can run tests like this yourself.

**Comment by indexzero** [comment]
@mmalecki Looks good. Will install `0.5.x` on my machine tonight and run the tests. Are you just compiling the latest on your machine to test this? Or is there a good solution for switching between `0.4.x` and 0.5.x`. 

I know `n`, `nvm`, and `nave` are around, but I've never used them

**Comment by mmalecki** [comment]
@indexzero I'm using v0.5.9 as my "main" node - it's installed in `/usr/bin`.

For switching to previous versions I use `nvm` or `nave`, they're both really nice (haven't used `n` yet). Only difference is that `nave` opens up a subshell (so when you're done with some node version you can just `^D`) and `nvm` modifies environment variables (to clear things up you need to `nvm deactivate`).

`nave` is easier to start with. You just `sudo npm install -g nave`, `nave install <version>` and `nave use 0.4.12`.
To start with `nvm` you have to source it somewhere, for example in your `.bashrc`.

Remember to `export JOBS=<number-of-cores>` before you do anything - compilation using one core takes ages.

Also, please note that when running things using `sudo`, your main node installation will be used. For example, this is the case when running `haibu-carapace` tests.

**Comment by mmalecki** [comment]
This is ready for merge. Can someone review or should I just merge it?
Also, it would be awesome to have this `npm publish`ed.

**Comment by voodootikigod** [comment]
Nudge on this as I need it as well.

Thanks

**Comment by indexzero** [comment]
@mmalecki This looks fine. It's just require.paths and assert.lengthOf. Merge at will.

**Comment by indexzero** [comment]
@mmalecki actually I'll do this quickly and publish it to npm. It's backwards compatible with 0.4.

**Comment by indexzero** [comment]
Done. Published to npm as `cloudfiles@0.3.1`

**Pull request merged**
