### PR TITLE
Node's HTTP(S) and Streams for uploading files 

### PR DESCRIPTION
**Pull request by kschzt**
Hi,

I rewrote the rackspaceCurl method using Node's HTTP(S) and Streams. This is so that I can provide a custom in-memory Stream.
- Use Node's HTTP(S) and Streams to upload files
- Renamed rackspaceCurl to rackspaceRequest
- Allow providing custom Stream
- Add test for custom stream

All tests pass.

BR,

Jak

### CODE REVIEW

**Comment by Marak** [comment]
Ohh heh, perhaps node's core HTTPS API actually works now? :-D

@indexzero will definitely take a look at this. Thanks!

**Comment by kschzt** [comment]
Added req.end() and res.destroy() so the request is ended and the socket is explicitly closed after response.

**Comment by kschzt** [comment]
Added Expect: 100-continue header, fixes larger file uploads.

**Comment by indexzero** [comment]
@kschzt I will look at this in the next couple of days. At first glace it seems like the `.rackspaceRequest()` method could be rolled into the existing `.rackspace()` method. I broke them out into two methods originally because large file uploads over HTTPS didn't work properly in node. That was `0.3.x` though, so I'm sure it's better now.

**Comment by robinvdvleuten** [comment]
Can't wait for the stream functionality! When is it planned to add this to the master branch?

**Comment by indexzero** [comment]
@RobinvdVieuten Sometime soon, some other things on our plate first

**Comment by robinvdvleuten** [comment]
@indexzero I will use the version of @kschzt in the meantime then. I can imagine that you have a lot on your plate with all that awesome modules you are developing ;)

**Comment by indexzero** [comment]
@RobinvdVleuten @kschzt This is now merged into the `0.3.x` branch. I made some pretty significant changes to take advantage of the stream objects returned from the latest version(s) of [request)(http://github.com/mikeal/request). 

Passing all tests, but I'm hold off on publishing until I can make some new tests to large file uploads (i.e. `> ~1.5Mb`)

**Comment by indexzero** [comment]
@RobinvdVleuten @kschzt This is now merged into master and published to npm as `cloudfiles@0.3.0`.

**Comment by robinvdvleuten** [comment]
Great! Thanks for that @indexzero

**Pull request closed without merging**
