### PR TITLE
Add reconnect support as cloudfiles invalidates tokens every 24 hours.

### PR DESCRIPTION
**Pull request by STRML**
I have been running node-cloudfiles in production for a while to run an image uploader and have noticed that every once in a while the uploader stops working.

As it turns out, Cloudfiles invalidates your accessToken every 24 hours.

This pull request contains the necessary code to detect a 401, attempt a reAuth, and restart the previous failed request.

### CODE REVIEW

**Comment by ajostergaard** [comment]
What if the upload was a stream not a file? :(

**Comment by ajostergaard** [comment]
Wouldn't it be better to timestamp the last auth and before each request check that it hasn't been 24 hours and if it has then quickly re-auth before sending the request? At the moment I'm avoiding the problem by re-authing before every request. :(

**Comment by STRML** [comment]
That might work better, assuming that the auth time always remains 24 hours. Why does the current code not work for you?

**Comment by ajostergaard** [comment]
It seems the 24 hours is fairly solid: "Auth tokens are valid for a 24 hours. Once a token expires, you must request a new one." (From the Rackspace CloudFiles dev guide).

My main concern with this fix is that it breaks if the upload is a stream - of course it would be possible to add a bunch of stuff to handle retrying any kind of failed attempt but it all starts getting very messy.

**Comment by indexzero** [comment]
This library has been deprecated. Please make all future commits Rackspace support on `pkgcloud`:

https://github.com/nodejitsu/pkgcloud
http://blog.nodejitsu.com/introducing-pkgcloud

I'll add a deprecation notice to the README.md for this project now. The Rackspace provider in `pkgcloud` could use a bunch of the recent fixed on node-cloudfiles, any help makes you a HERO in my book :+1:

**Comment by ajostergaard** [comment]
That explains a lot - thanks for the update. :)

**Comment by STRML** [comment]
@ajostergaard - the posted patch is hooked into the common.rackspace function, which should be reused for all queries regardless of what they are. I can see why it breaks on streams though. I would say the smart thing to do would be to put the reauth code right there in that method like you suggested.

It doesn't seem like pkgcloud is tested or working at all for rackspace. I'm seeing the File module calling 'common.rackspace' (much like node-cloudfiles) but common is not defined in that module or anywhere else I can see. It seems this lib is still the only choice.

**Comment by ajostergaard** [comment]
@STRML - pkgcloud is working for me. It even seems to handle authenticating automatically so perhaps won't suffer from this issue at all. Time will tell ... And if it does have the same issue I'll just auth on each request like I am now (or find the time to fix it).

**Pull request closed without merging**
